/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.julien.openpaceandroidstudiotest.models;

public class SWIGTYPE_p_CVC_CERTIFICATE_DESCRIPTION {
  private transient long swigCPtr;

  protected SWIGTYPE_p_CVC_CERTIFICATE_DESCRIPTION(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_CVC_CERTIFICATE_DESCRIPTION() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_CVC_CERTIFICATE_DESCRIPTION obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}
