/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.julien.openpaceandroidstudiotest;

public interface eacConstants {
  public final static int EAC_TR_VERSION_2_01 = eacJNI.EAC_TR_VERSION_2_01_get();
  public final static int EAC_TR_VERSION_2_02 = eacJNI.EAC_TR_VERSION_2_02_get();
  public final static int EAC_ID_PACE = eacJNI.EAC_ID_PACE_get();
  public final static int EAC_ID_CA = eacJNI.EAC_ID_CA_get();
  public final static int EAC_ID_TA = eacJNI.EAC_ID_TA_get();
  public final static int EAC_ID_EAC = eacJNI.EAC_ID_EAC_get();
}
