/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.7
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.julien.openpaceandroidstudiotest;


public class SWIGTYPE_p_CVC_CERT {
  private transient long swigCPtr;

  protected SWIGTYPE_p_CVC_CERT(long cPtr, @SuppressWarnings("unused") boolean futureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_CVC_CERT() {
    swigCPtr = 0;
  }

  protected static long getCPtr(SWIGTYPE_p_CVC_CERT obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

